### ISSUE TITLE
version and name not honoured

### ISSUE THREAD

**Issue by imod** [dart-ogurets/dart-openapi-maven#5]
I have the following maven plugin configuration:

```
...
     <version>0.0.1-SNAPSHOT</version>
...
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>4.0.0</version>
				<dependencies>
					<dependency>
						<groupId>com.bluetrainsoftware.maven</groupId>
						<artifactId>openapi-dart-generator</artifactId>
						<version>2.8</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>mplan-api</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>generate-sources</phase>
						<configuration>
							<!-- <output>${project.build.directory}/generated-sources/dart</output> -->
							<output>../dart/mplan_api/</output>
							<inputSpec>${project.basedir}/src/main/openapi/mplan-api.yaml</inputSpec>
							<language>dart2-api</language>
							<enablePostProcessFile>true</enablePostProcessFile>
							<additionalProperty>
								pubName=mplan_api
								pubVersion=${project.version}
							</additionalProperty>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

but my generated `pubspec.yaml` does look like this:

```
name: openapi
version: 1.0.0
description: OpenAPI API client
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  dio: '>= 3.0.3 <4.0.0'
  openapi_dart_common: ^2.0.0
collection: ^1.14.11
dev_dependencies:
  test: ^1.3.0
```

so name and version are not taken as configured in the `pom.xml`, it should be:

```
name: mplan_api
version: 0.0.1-SNAPSHOT
...
```
