### ISSUE TITLE
required, nullable class variables are not generated as nullable

### ISSUE THREAD

**Issue by NANASHI0X74** [dart-ogurets/dart-openapi-maven#58]
example schema:
```yaml
components:
  schemas:
    UserDetail:
      type:object
      properties:
        invite:
          type: boolean
          readOnly: true
          nullable: true
      required:
      - invite
```

class generated will have invite as `late bool invite` and throw a deserializationerror when deserializing objects that have that property as null.
